### ISSUE TITLE
Things to discuss before Chris leaves

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/meta#25]
I'm leaving on Wednesday morning (flight @ 11am). We have a few more opportunities for discussions and brainstorming before I go.

What shall we prioritize? I think we are relatively clear on the high-level build picture. So that means we can dive in on one of the steps in-between if it'd be particularly helpful.

Some ideas from me:

* Discussing what system we'll use for notebook cacheing and running (maybe related to https://github.com/ExecutableBookProject/myst_parser/pull/47)
  * Is the "cache" layer an on-disk collection of notebooks, or some kind of database representation of notebooks
    * The plan is to use a "Jupyter Cache" tool that can do either (and is backend-agnostic). 
  * If so, does that mean we need to build a bunch of sphinx components that utilize a database instead of notebooks
    * Ultimately it'll probably be a Sphinx Parser that knows how to pull from a jupyter cache and put it into the Sphinx AST. This will probably live next to the "ipynb sphinx parser"
  * And if that's the case, shall we still build a proper `ipynb` sphinx parser in case others want to read notebooks in to Sphinx directly
    * Yes, chris h will give this a shot.
* How will the HTML/PDF builders use the Sphinx AST in their outputs? Maybe @mmcky can describe this process since I'll need to understand it for hooking up Jupyter Book CSS/JS
  - Parse the ipynb outputs into a "MimeNode" at the parsing stage so it's in the AST. Then build a post-transform that will loop through the MIMENodes and convert them to Sphinx AST objects depending on the "builder" type (this is where the right mimebundle gets chosen)
* What kind of meeting cadence shall we have in the next few weeks while @chrisjsewell is still in Australia?
  - Meet once a week and follow the JupyterHub meeting team practices to plan an execute the meeting.
* MyST-based notebook representation syntax

**Comment by mmcky** [comment]
thanks @choldgraf -- good ideas. Aakash and I would be happy to run through `builder` and `translator` class structures for `sphinx`. 

additional ideas:

- development of a project specification (wiki style) that can change over time. One idea is to use a `sphinx` repository to maintain it. Usually these documents are table heavy though and this is an area where markup doesn't shine :-)

- review of test set infrastructure to ease contributions as they develop over time.
