### ISSUE TITLE
Core design constraints and guiding principles

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/meta#5]
Hey all - I've found that it is helpful to determine two things to guide the design/development of projects:

* **Core constraints** . These are things that *must* be satisfied by the final output, and can help in narrowing the space of possibilities to focus on the most-impactful product.
* **Guiding principles**. These are general approaches to take when trying to decide between multiple options. They aren't hard rules but heuristics to follow.

(as a general rule, it's OK to have more principles, and we should try to minimize the number of core restraints)

Would folks be interested in adding their own thoughts / brainstorm to this list? I'll add a comment with some quick ones that come to mind from my perspective - these don't need to be strict rules if we wish, but at the least it's a way to see where we're coming from.

**Comment by choldgraf** [comment]
Here are a few that come to my mind off the top of my head, I'll try to edit / update over time.

# Core constraints

* Support content that is stored in text-based format as well
  as in `ipynb` format.
* Support polyglot content

# Guiding principles

* Support casual users equally to power users. Complicating the
  feature space to support a "power user feature" should be done
  with great care.
* Don't try to do everything with this tool. It should
  be about reducing what's possible and focusing it on publishing documents.
  * Expand the user-facing API or the total feature set of the tool with great care.
  (as an example, nbconvert is under-utilized because it is too complex to use and maintain)
* Where there are markdown syntax or structure standards, use those, don't create a new markdown standard.
  * If any new syntax or standard is introduced (e.g. if we
    really do want to create a custom text-based version of notebooks that deviates from tools people already use, this should be done as a broader effort w/ the Jupyter community)
* Where there is pre-existing tech, use that, don't create new tech.
  * Decisions to build new tech should be done after a review of other options as well as pros/cons of each.
* Design for a future with volunteer or under-resourced developers. The technology should be easy for motivated newcomers to read, understand, and modify/improve. This might mean *not* making the "technically best solution" so that we can take an approach that is simpler to wrap one's head around.
* Minimize the total number of lines of code we need to maintain.

**Comment by jstac** [comment]
This is really valuable!   

I'll add to the core constraints but perhaps we should take up your suggestion of editing in the wiki @choldgraf, while reserving the issue tracker for "actionable" items?  If you agree then I'll set up a wiki and shift this over.

**Comment by choldgraf** [comment]
sounds good to me!

**Comment by jstac** [comment]
Thanks for starting this @choldgraf .  

I shifted the content to https://github.com/ExecutableBookProject/meta/wiki/Core-design-constraints-and-guiding-principles and hence am closing the issue.

I added a bit more detail into core constraints.  It might be overkill but it does reflect what we have undertaken to provide.
