### ISSUE TITLE
Move my sphinx-copybutton repository here?

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/meta#55]
Hey all - how do folks feel about me moving my sphinx-copybutton repository to the `EBP` organization? I think this is a nice longer-term home for sphinx-copybutton rather than my personal github repo. I can standardize the testing infrastructure so that it is more similar to the other EBP projects.

https://github.com/choldgraf/sphinx-copybutton

**Comment by mmcky** [comment]
hey @choldgraf a collection of tools in `ebp` sounds like a good idea to me.

**Comment by chrisjsewell** [comment]
+1

**Comment by choldgraf** [comment]
Done!https://github.com/ExecutableBookProject/sphinx-copybutton
