### ISSUE TITLE
Have a show-and-tell meeting?

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/meta#7]
I think it'd be fun and interesting to do a quick show-and-tell of our various build systems. Are folks interested in having a one-or-so-hour meeting where we each get 30 minutes to give a brief overview of our respective build systems? E.g., design philosophy, what technical choices are made, pros/cons, etc?

**Comment by gregcaporaso** [comment]
Great idea - I'm in!

**Comment by jstac** [comment]
+1

**Comment by mmcky** [comment]
+1

**Comment by choldgraf** [comment]
ok, so when would we like this meeting to be? I think we should move beyond the +1 stage and to the planning stage :-)

I will semi-randomly say sometime next Wednesday - does that work for folks? Could also try to find a time this week if that works better

**Comment by mmcky** [comment]
While discussing times -- perhaps we should lock in a standard monthly meeting time also?

I'd be free next Tuesday (AEST) / Wednesday (US Pacific)

**Comment by choldgraf** [comment]
Oh gosh, I just realized that all of our meetings will likely be on two days of the week. That'll be fun :-)

A monthly meeting time sounds great to me. What kinds of time windows should we shoot for?

**Comment by gregcaporaso** [comment]
Next Wed (11/20) works well for me outside of 11:30am-1pm US Mountain Time.

**Comment by gregcaporaso** [comment]
Looks like afternoons for @choldgraf and I and mornings (plus one day) for @mmcky and @jstac would make sense? 

Could we plan for 2pm US Mountain Time / 1pm US Pacific Time [Wed 11/20] and  8am Canberra Time [Thurs 11/21] for our next meeting? And then maybe set up a recurring call on that meeting? I think I got those times right.

I can send a Zoom invite for this if that's helpful.

**Comment by choldgraf** [comment]
I could do 2:40pm California time that day...any chance we could push to then?

**Comment by jstac** [comment]
That works for me.  (=9:40am thurs 11/21 Canberra time)

**Comment by choldgraf** [comment]
Hey all - I know we haven't all confirmed this time yet, but I created a calendar invite and sent it to you all just to put a pin in that time slot in case it does work

**Comment by gregcaporaso** [comment]
That time also works for me.

**Comment by jstac** [comment]
Just letting you know that meeting has come up which I can't shift or avoid, so I'll only be online for the first 15 mins.  @mmcky is the guy who can tell you about Jupinx so this won't be a big issue.  I'll catch up with him afterwards and get a summary of the discussion.

**Comment by choldgraf** [comment]
If y'all want, my 2pm (california time) meeting got canceled, so I can now do the original 2pm Pacific time meeting slot if that works for others.

**Comment by gregcaporaso** [comment]
The original time still works for me, but I'd need to know soon because I'll have two people from my lab joining. It's pretty early in Canberra right now though, so I'm guessing we might not hear back in time to change it.

**Comment by mmcky** [comment]
I will only get in around 9:30am so I wouldn’t be able to join until then. So 9:40 works better for me.

**Comment by gregcaporaso** [comment]
Let's leave it at 40 minutes after the hour then. 

I created a Zoom meeting that we can use. Does that work? 

Greg Caporaso is inviting you to a scheduled Zoom meeting.

Topic: Executable Book project meeting
Time: Nov 20, 2019 03:40 PM Arizona

Join Zoom Meeting
https://nau.zoom.us/j/658568146

Meeting ID: 658 568 146

One tap mobile
+16699006833,,658568146# US (San Jose)
+16468769923,,658568146# US (New York)

Dial by your location
        +1 669 900 6833 US (San Jose)
        +1 646 876 9923 US (New York)
Meeting ID: 658 568 146
Find your local number: https://nau.zoom.us/u/ay4oVWNCm

**Comment by choldgraf** [comment]
Hey all - it was great meeting with everybody yesterday, and having a chance to chat about all of this stuff with you. Now I am sad that we don't all live in the same city :-)

Anyway, I just copied over the notes that I took in the hackmd to a new wiki page:

https://github.com/ExecutableBookProject/meta/wiki/Meetings

Please feel free to edit / add / delete as you wish - I was taking very freeform notes without thinking a bunch, and I didn't clean them up at all before pasting in here.

Per @mmcky's suggestion I also added a short summary of the top-level takeaways from the Jupyter Book portion of the show n' tell. I'd love to hear what y'all think.

https://github.com/ExecutableBookProject/meta/wiki/Meetings#jupyter-book

**Comment by gregcaporaso** [comment]
Hi all,
Great meeting yesterday! We're very much looking forward to this project, and it spurred some additional discussion on our end about use cases for this project. 

I added Matt (@thermokarst) and Evan (@ebolyen) from my group to this organization, and will make a couple of edits/additions to wiki page now.

**Comment by mmcky** [comment]
thanks @choldgraf great meeting notes. Thanks for taking them down and adding a wiki. I will take a look today and make any edits etc. 

Wecome @thermokarst and @ebolyen
